import '../assets/styles/globals.css';
import { AppProviders } from './providers/AppProviders';

export const metadata = {
  title: 'Welcome to platform',
  description: 'Generated by create-nx-workspace',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {

  return (
    <html lang="en">
      <body>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
