import { AppLayout } from '../Layout/AppLayout';
import '../assets/styles/globals.css';

export const metadata = {
  title: 'Welcome to platform',
  description: 'Generated by create-nx-workspace',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
