import './global.css';
import "../assets/styles/globals.css";

export const metadata = {
  title: 'Welcome to platform',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
